--
-- PostgreSQL database dump
--

\restrict JkDcJwCljediQR2HvhQmEaIErxR6WonBs1HIfkPGupGJCBOJf2ANNrQXIheJiQt

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 14.19 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_customuser; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.accounts_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    phone_number character varying(15)
);


ALTER TABLE public.accounts_customuser OWNER TO maryam;

--
-- Name: accounts_customuser_groups; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.accounts_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_customuser_groups OWNER TO maryam;

--
-- Name: accounts_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.accounts_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.accounts_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser_user_permissions; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.accounts_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_customuser_user_permissions OWNER TO maryam;

--
-- Name: accounts_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.accounts_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_ledgerentry; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.accounts_ledgerentry (
    id bigint NOT NULL,
    transaction_type character varying(10) NOT NULL,
    amount numeric(12,2) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    account_id bigint NOT NULL
);


ALTER TABLE public.accounts_ledgerentry OWNER TO maryam;

--
-- Name: accounts_ledgerentry_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.accounts_ledgerentry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_ledgerentry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_order; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.accounts_order (
    id bigint NOT NULL,
    order_type character varying(4) NOT NULL,
    quantity integer NOT NULL,
    price numeric(12,2) NOT NULL,
    status character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    account_id bigint NOT NULL,
    stock_id bigint NOT NULL
);


ALTER TABLE public.accounts_order OWNER TO maryam;

--
-- Name: accounts_order_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.accounts_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_stock; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.accounts_stock (
    id bigint NOT NULL,
    ticker character varying(10) NOT NULL,
    name character varying(100) NOT NULL,
    exchange character varying(50) NOT NULL,
    price numeric(12,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.accounts_stock OWNER TO maryam;

--
-- Name: accounts_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.accounts_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_tradingaccount; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.accounts_tradingaccount (
    id bigint NOT NULL,
    account_number character varying(100) NOT NULL,
    balance numeric(12,2) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    status boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.accounts_tradingaccount OWNER TO maryam;

--
-- Name: accounts_trading_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.accounts_tradingaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_trading_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_tradingposition; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.accounts_tradingposition (
    id bigint NOT NULL,
    stock_ticker character varying(10) NOT NULL,
    quantity integer NOT NULL,
    avg_price numeric(12,2) NOT NULL,
    account_id bigint NOT NULL
);


ALTER TABLE public.accounts_tradingposition OWNER TO maryam;

--
-- Name: accounts_tradingposition_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.accounts_tradingposition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_tradingposition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO maryam;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO maryam;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO maryam;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO maryam;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO maryam;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO maryam;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: maryam
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: maryam
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO maryam;

--
-- Data for Name: accounts_customuser; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.accounts_customuser (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, phone_number) FROM stdin;
8	pbkdf2_sha256$1000000$mqow2yXf67PMK60fZJjdTi$Q2zEtBdwDyZycexRWFinTRtetwGvHs/7gwKV2eZ01No=	\N	f	usman				f	t	2025-09-09 18:45:40.415+05	\N
10	pbkdf2_sha256$1000000$eQA3QVnKF9bfNSzQWxv8Bc$TLu8WiVrafcBGnfxTOxUOgK+2RJSmmjhnMdiyzbXFkE=	\N	f	Tarfa			tarfa34@gmail.com	f	t	2025-09-10 13:54:08.589+05	\N
11	pbkdf2_sha256$1000000$TaXTskQr40X2zmMZFueU6Y$1cueB2ubOVo/biUsUX7SOqYXaQaVbB3AxYGdIHQnFm8=	\N	f	Nazia			nazia@gmail.com	f	t	2025-09-10 13:57:15.114+05	\N
12	pbkdf2_sha256$1000000$zQGKkaiGHj8mxdka14PiCR$aMK+y4ZyL497Bd/49iqe9590prEgxSlOXojX3w3StCg=	\N	f	Mehwish			mehwish34@gmail.com	f	t	2025-09-10 13:59:32.449+05	\N
13	pbkdf2_sha256$1000000$GRErhToXHbgxDZ9uvqASr0$X5TGyOA6UA9y/Dy4xA2KrkuC3c0wJkGCnpQkZxbidqo=	\N	f	Saima			saima34@gmail.com	f	t	2025-09-10 14:09:38.482+05	\N
14	pbkdf2_sha256$1000000$9mNZiDS3HRu5SYY8kWKPjE$llx+F1IX+nEi3OOG+2Pjy6GRA9kqoGH/TO3vJ2VAhnw=	\N	f	ayesha			ayesha@gmail.com	f	t	2025-09-12 13:33:33.12+05	\N
1	pbkdf2_sha256$1000000$HWaYdVC4FA8JBk8yecgfCl$urNsckpnGzLR3t5kJUiz6DlkBD5LVwro52zsXvlpaew=	2025-09-24 11:56:48.740408+05	t	admin			admin34@gmail.com	t	t	2025-09-09 16:50:59.813+05	\N
15	pbkdf2_sha256$1000000$hvTXajSdIoyM39VxM8bygu$KUQmZdZxxSlS5QWhuXcMI4tBSvglGiMZrux5Mdckig0=	\N	f	saba			saba@gmail.com	f	t	2025-09-26 12:49:10.536997+05	\N
17	pbkdf2_sha256$1000000$gvnw1Z8woMZtwAZwt916tT$9+1yCOjN7WBxMuMPnhn+Qvn4UuqGNGSrnBgrZKo+J3Q=	\N	f	Fizza			fizzaali@gmail.com	f	t	2025-09-26 12:56:43.105288+05	031138382726
\.


--
-- Data for Name: accounts_customuser_groups; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.accounts_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.accounts_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: accounts_ledgerentry; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.accounts_ledgerentry (id, transaction_type, amount, "timestamp", account_id) FROM stdin;
1	deposit	1000.00	2025-09-10 16:05:54.537+05	8
2	withdraw	200.00	2025-09-10 16:06:41.282+05	8
3	withdraw	290.20	2025-09-16 19:09:01.544671+05	8
4	withdraw	435.30	2025-09-16 19:15:35.343741+05	8
5	deposit	412.60	2025-09-17 12:23:25.32236+05	8
6	deposit	412.60	2025-09-17 16:28:25.306723+05	8
7	withdraw	412.60	2025-09-17 18:26:20.858834+05	8
8	withdraw	412.60	2025-09-17 18:27:29.028095+05	8
9	withdraw	412.60	2025-09-17 18:37:51.708682+05	8
10	withdraw	412.60	2025-09-17 18:39:32.903424+05	8
11	withdraw	412.60	2025-09-17 18:44:30.680274+05	8
12	withdraw	412.60	2025-09-17 18:48:30.845584+05	8
13	withdraw	412.60	2025-09-17 18:51:15.270117+05	8
14	withdraw	1029.20	2025-09-30 12:19:27.198307+05	12
15	deposit	1029.20	2025-09-30 12:42:29.501847+05	12
\.


--
-- Data for Name: accounts_order; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.accounts_order (id, order_type, quantity, price, status, created_at, account_id, stock_id) FROM stdin;
6	SELL	2	200.50	PENDING	2025-09-17 16:03:24.924999+05	8	1
7	SELL	2	200.50	PENDING	2025-09-17 16:04:00.673851+05	8	1
8	SELL	2	200.50	PENDING	2025-09-17 16:06:14.322652+05	8	1
9	SELL	2	200.50	PENDING	2025-09-17 16:06:38.588641+05	8	1
10	SELL	2	200.50	PENDING	2025-09-17 16:17:43.095269+05	8	1
11	SELL	2	200.50	PENDING	2025-09-17 16:18:22.741064+05	8	1
12	SELL	2	200.00	PENDING	2025-09-17 16:18:39.618646+05	8	1
13	SELL	2	200.00	PENDING	2025-09-17 16:24:20.410211+05	8	1
14	SELL	2	200.00	PENDING	2025-09-17 16:26:51.911628+05	8	1
15	SELL	2	206.30	COMPLETED	2025-09-17 16:28:25.207667+05	8	1
5	SELL	2	200.50	PENDING	2025-09-17 16:00:46.377088+05	8	1
16	BUY	2	206.30	COMPLETED	2025-09-17 18:26:20.794959+05	8	1
17	BUY	2	206.30	COMPLETED	2025-09-17 18:27:28.98046+05	8	1
18	BUY	2	206.30	COMPLETED	2025-09-17 18:37:51.641371+05	8	1
19	BUY	2	206.30	COMPLETED	2025-09-17 18:39:32.85112+05	8	1
20	BUY	2	206.30	COMPLETED	2025-09-17 18:44:30.635355+05	8	1
21	BUY	2	206.30	COMPLETED	2025-09-17 18:48:30.782655+05	8	1
22	BUY	2	206.30	COMPLETED	2025-09-17 18:51:15.220094+05	8	1
23	SELL	4	120.04	PENDING	2025-09-23 13:07:34.660065+05	9	3
24	BUY	2	514.60	COMPLETED	2025-09-30 12:19:27.137423+05	12	3
27	SELL	2	514.60	COMPLETED	2025-09-30 12:42:29.395432+05	12	3
28	SELL	2	221.00	CANCELLED	2025-09-30 12:45:43.115249+05	12	3
29	SELL	2	221.00	CANCELLED	2025-09-30 12:55:59.72194+05	12	3
\.


--
-- Data for Name: accounts_stock; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.accounts_stock (id, ticker, name, exchange, price, created_at, updated_at) FROM stdin;
3	MSFT	Microsoft Corp.	NASDAQ	514.60	2025-09-11 13:53:15.621+05	2025-09-30 16:50:02.484908+05
2	GOOGL	Alphabet Inc.	NASDAQ	244.05	2025-09-11 13:53:15.619+05	2025-09-30 16:50:03.163206+05
5	AMZN	Amazon.com Inc.	NASDAQ	222.17	2025-09-11 13:53:15.624+05	2025-09-30 16:50:03.908039+05
4	TSLA	Tesla Inc.	NASDAQ	443.21	2025-09-11 13:53:15.622+05	2025-09-30 16:50:04.574591+05
1	AAPL	Apple Inc.	NASDAQ	254.43	2025-09-11 13:49:44.786+05	2025-09-30 16:50:05.3389+05
\.


--
-- Data for Name: accounts_tradingaccount; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.accounts_tradingaccount (id, account_number, balance, created_at, status, user_id) FROM stdin;
10	27a8e7c6-8270-48da-b554-3d4a1a41dd58	200.00	2025-09-26 12:49:11.061066+05	t	15
9	0685a220-1b83-439f-8cb6-3fe1c441d32d	25670.00	2025-09-12 13:33:33.669+05	t	14
4	475de640-baa3-4d7d-97b5-48e48b98f36d	13026.00	2025-09-10 13:38:04.662+05	t	1
5	9d84228d-ee7e-4120-8d4a-37fc593c5c5a	12350.00	2025-09-10 13:54:09.141+05	t	10
6	bf88d1c1-2a2b-4112-9569-84b374776a4b	120.00	2025-09-10 13:57:15.654+05	t	11
2	d100ab5e-bfc0-41c0-b09f-e0a0b7267ebc	7680.00	2025-09-09 18:45:40.931+05	t	8
7	5a87f862-fc6f-43a4-ab1e-f0413d79dc4c	7260.00	2025-09-10 13:59:32.993+05	t	12
8	7edc6e88-c805-4908-a60b-281e43b6dfa4	9211.50	2025-09-10 14:09:39.044+05	t	13
12	3f8e06c0-6ced-4b01-98b0-e8fd41efc53f	12000.00	2025-09-26 12:56:43.572194+05	t	17
\.


--
-- Data for Name: accounts_tradingposition; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.accounts_tradingposition (id, stock_ticker, quantity, avg_price, account_id) FROM stdin;
3	TSLA	5	300.00	8
4	MSFT	2	250.00	8
5	AMZN	5	145.10	8
1	AAPL	20	189.42	8
6	AAPL	3	170.00	4
10	TSLA	12	270.00	2
11	AMZN	12	169.00	12
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_customuser
22	Can change user	6	change_customuser
23	Can delete user	6	delete_customuser
24	Can view user	6	view_customuser
25	Can add trading	7	add_trading
26	Can change trading	7	change_trading
27	Can delete trading	7	delete_trading
28	Can view trading	7	view_trading
29	Can add trading account	7	add_tradingaccount
30	Can change trading account	7	change_tradingaccount
31	Can delete trading account	7	delete_tradingaccount
32	Can view trading account	7	view_tradingaccount
33	Can add trading position	8	add_tradingposition
34	Can change trading position	8	change_tradingposition
35	Can delete trading position	8	delete_tradingposition
36	Can view trading position	8	view_tradingposition
37	Can add ledger entry	9	add_ledgerentry
38	Can change ledger entry	9	change_ledgerentry
39	Can delete ledger entry	9	delete_ledgerentry
40	Can view ledger entry	9	view_ledgerentry
41	Can add stock	10	add_stock
42	Can change stock	10	change_stock
43	Can delete stock	10	delete_stock
44	Can view stock	10	view_stock
45	Can add order	11	add_order
46	Can change order	11	change_order
47	Can delete order	11	delete_order
48	Can view order	11	view_order
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-09-09 18:19:10.066+05	1	maryam - abbc0ed9-e09f-457a-adb9-b4da0fe6e8f8	1	[{"added": {}}]	7	1
2	2025-09-10 13:37:45.528+05	9	rabia	3		6	1
3	2025-09-10 13:37:45.528+05	7	ahana	3		6	1
4	2025-09-10 13:37:45.528+05	6	merry	3		6	1
5	2025-09-10 13:37:45.528+05	5	Aiaman	3		6	1
6	2025-09-10 13:37:45.528+05	4	ayesha	3		6	1
7	2025-09-10 13:37:45.528+05	3	laiba	3		6	1
8	2025-09-10 13:38:04.663+05	4	admin - 475de640-baa3-4d7d-97b5-48e48b98f36d	1	[{"added": {}}]	7	1
9	2025-09-16 19:01:45.314851+05	8	Saima - 7edc6e88-c805-4908-a60b-281e43b6dfa4	2	[{"changed": {"fields": ["Balance"]}}]	7	1
10	2025-09-17 16:32:03.170831+05	5	Saima-SELL-2 of AAPL	2	[]	11	1
11	2025-09-22 18:00:58.718348+05	1	AAPL-Apple Inc.	2	[{"changed": {"fields": ["Price"]}}]	10	1
12	2025-09-22 18:03:25.253416+05	2	GOOGL-Alphabet Inc.	2	[{"changed": {"fields": ["Price"]}}]	10	1
13	2025-09-23 13:07:34.666369+05	23	ayesha-SELL-4 of MSFT	1	[{"added": {}}]	11	1
14	2025-09-26 12:56:11.069277+05	16	Fizza	3		6	1
15	2025-09-26 13:09:10.045526+05	12	Fizza - 3f8e06c0-6ced-4b01-98b0-e8fd41efc53f	2	[{"changed": {"fields": ["Balance"]}}]	7	1
16	2025-09-26 13:09:17.373837+05	10	saba - 27a8e7c6-8270-48da-b554-3d4a1a41dd58	2	[{"changed": {"fields": ["Balance"]}}]	7	1
17	2025-09-26 13:09:27.715396+05	9	ayesha - 0685a220-1b83-439f-8cb6-3fe1c441d32d	2	[{"changed": {"fields": ["Balance"]}}]	7	1
18	2025-09-26 13:09:47.587486+05	4	admin - 475de640-baa3-4d7d-97b5-48e48b98f36d	2	[{"changed": {"fields": ["Balance"]}}]	7	1
19	2025-09-26 13:09:56.37351+05	5	Tarfa - 9d84228d-ee7e-4120-8d4a-37fc593c5c5a	2	[{"changed": {"fields": ["Balance"]}}]	7	1
20	2025-09-26 13:10:03.837498+05	6	Nazia - bf88d1c1-2a2b-4112-9569-84b374776a4b	2	[{"changed": {"fields": ["Balance"]}}]	7	1
21	2025-09-26 13:10:08.441298+05	1	maryam - abbc0ed9-e09f-457a-adb9-b4da0fe6e8f8	2	[]	7	1
22	2025-09-26 13:10:16.727944+05	2	usman - d100ab5e-bfc0-41c0-b09f-e0a0b7267ebc	2	[{"changed": {"fields": ["Balance"]}}]	7	1
23	2025-09-26 13:10:23.84788+05	7	Mehwish - 5a87f862-fc6f-43a4-ab1e-f0413d79dc4c	2	[{"changed": {"fields": ["Balance"]}}]	7	1
24	2025-09-26 13:10:27.264007+05	8	Saima - 7edc6e88-c805-4908-a60b-281e43b6dfa4	2	[]	7	1
25	2025-09-26 14:04:26.702969+05	6	TradingPosition object (6)	1	[{"added": {}}]	8	1
26	2025-09-26 14:05:24.94482+05	7	TradingPosition object (7)	1	[{"added": {}}]	8	1
27	2025-09-26 14:05:51.749988+05	8	TradingPosition object (8)	1	[{"added": {}}]	8	1
28	2025-09-26 14:26:36.213538+05	8	TradingPosition object (8)	3		8	1
29	2025-09-26 14:27:58.184521+05	9	TradingPosition object (9)	1	[{"added": {}}]	8	1
30	2025-09-26 14:28:47.061829+05	10	TradingPosition object (10)	1	[{"added": {}}]	8	1
31	2025-09-26 14:29:20.407839+05	10	TradingPosition object (10)	2	[{"changed": {"fields": ["Stock ticker"]}}]	8	1
32	2025-09-26 20:54:04.387208+05	2	maryam	3		6	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	accounts	customuser
7	accounts	tradingaccount
8	accounts	tradingposition
9	accounts	ledgerentry
10	accounts	stock
11	accounts	order
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-09-12 20:10:11.759184+05
2	contenttypes	0002_remove_content_type_name	2025-09-12 20:10:11.764965+05
3	auth	0001_initial	2025-09-12 20:10:11.792001+05
4	auth	0002_alter_permission_name_max_length	2025-09-12 20:10:11.796457+05
5	auth	0003_alter_user_email_max_length	2025-09-12 20:10:11.800846+05
6	auth	0004_alter_user_username_opts	2025-09-12 20:10:11.805107+05
7	auth	0005_alter_user_last_login_null	2025-09-12 20:10:11.809361+05
8	auth	0006_require_contenttypes_0002	2025-09-12 20:10:11.810426+05
9	auth	0007_alter_validators_add_error_messages	2025-09-12 20:10:11.814778+05
10	auth	0008_alter_user_username_max_length	2025-09-12 20:10:11.819237+05
11	auth	0009_alter_user_last_name_max_length	2025-09-12 20:10:11.824474+05
12	auth	0010_alter_group_name_max_length	2025-09-12 20:10:11.82954+05
13	auth	0011_update_proxy_permissions	2025-09-12 20:10:11.833703+05
14	auth	0012_alter_user_first_name_max_length	2025-09-12 20:10:11.837665+05
15	accounts	0001_initial	2025-09-12 20:10:11.871517+05
16	accounts	0002_rename_trading_tradingaccount	2025-09-12 20:10:11.884424+05
17	accounts	0003_ledgerentry_tradingposition	2025-09-12 20:10:11.906638+05
18	accounts	0004_stock	2025-09-12 20:10:11.91213+05
19	admin	0001_initial	2025-09-12 20:10:11.926179+05
20	admin	0002_logentry_remove_auto_add	2025-09-12 20:10:11.933671+05
21	admin	0003_logentry_add_action_flag_choices	2025-09-12 20:10:11.94074+05
22	sessions	0001_initial	2025-09-12 20:10:11.946298+05
23	accounts	0005_order	2025-09-17 15:49:00.797816+05
24	accounts	0006_alter_ledgerentry_amount_alter_stock_price_and_more	2025-09-17 16:27:43.737672+05
25	accounts	0007_alter_tradingaccount_balance	2025-09-17 16:27:43.749958+05
26	accounts	0008_tradingposition_unique_account_stock	2025-09-26 14:27:08.612126+05
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: maryam
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
giogprj137ggsr5i6xrsyhfudimx7ma5	.eJxVjEEOwiAQRe_C2pCBdgq4dO8ZyACDVA0kpV0Z765NutDtf-_9l_C0rcVvnRc_J3EWSpx-t0DxwXUH6U711mRsdV3mIHdFHrTLa0v8vBzu30GhXr611TiEgTMnypZo0Iw5sEaIZoLAYB2bDGimEKOyOAIkZhfBOIekYBTvDwM0ODA:1uvy9X:K9vf3oK_ghHHeLyM9P5Sv9pktIHhjQFG7Q5-MN2LGUU	2025-09-23 18:12:55.03+05
z33xc9qn4p3zmao3xgtzs5c9ykkij9gb	.eJxVjEEOwiAQRe_C2pCBdgq4dO8ZyACDVA0kpV0Z765NutDtf-_9l_C0rcVvnRc_J3EWSpx-t0DxwXUH6U711mRsdV3mIHdFHrTLa0v8vBzu30GhXr611TiEgTMnypZo0Iw5sEaIZoLAYB2bDGimEKOyOAIkZhfBOIekYBTvDwM0ODA:1uvwsh:hEfKqUGKVBC8i7aEGmBP1qbY6HMbb3nQ8OK9_3S4-_Q	2025-09-23 16:51:27.838+05
z85oqkeszroktyza13i5v5pstyz2smmi	.eJxVjEEOwiAQRe_C2pCBdgq4dO8ZyACDVA0kpV0Z765NutDtf-_9l_C0rcVvnRc_J3EWSpx-t0DxwXUH6U711mRsdV3mIHdFHrTLa0v8vBzu30GhXr611TiEgTMnypZo0Iw5sEaIZoLAYB2bDGimEKOyOAIkZhfBOIekYBTvDwM0ODA:1ux5RH:iVaZxkQ6L0-vJOLcF1vq4JuWlsUL2OgzuE-2zSSxOM8	2025-09-26 20:11:51.838219+05
ufitt89iodvnqo1st1dm0vz02upbdiql	.eJxVjEEOwiAQRe_C2pCBdgq4dO8ZyACDVA0kpV0Z765NutDtf-_9l_C0rcVvnRc_J3EWSpx-t0DxwXUH6U711mRsdV3mIHdFHrTLa0v8vBzu30GhXr611TiEgTMnypZo0Iw5sEaIZoLAYB2bDGimEKOyOAIkZhfBOIekYBTvDwM0ODA:1uyUPr:VpLCU1mJL5JXhAJARVOdWKnFv4Ng5sqMpnt92ivFIHw	2025-09-30 17:04:11.850642+05
q3uqdfncivfnetgsukcfoffyykjs2z5w	.eJxVjEEOwiAQRe_C2pCBdgq4dO8ZyACDVA0kpV0Z765NutDtf-_9l_C0rcVvnRc_J3EWSpx-t0DxwXUH6U711mRsdV3mIHdFHrTLa0v8vBzu30GhXr611TiEgTMnypZo0Iw5sEaIZoLAYB2bDGimEKOyOAIkZhfBOIekYBTvDwM0ODA:1v0fz2:wQWU1JHg85q9XWnTNp6gSNSylqWH0oZGjz7GU210itY	2025-10-06 17:49:32.230208+05
onurxe7hswxvy53u5jc5341r0crsuuht	.eJxVjEEOwiAQRe_C2pCBdgq4dO8ZyACDVA0kpV0Z765NutDtf-_9l_C0rcVvnRc_J3EWSpx-t0DxwXUH6U711mRsdV3mIHdFHrTLa0v8vBzu30GhXr611TiEgTMnypZo0Iw5sEaIZoLAYB2bDGimEKOyOAIkZhfBOIekYBTvDwM0ODA:1v1JQm:0AVG6vNYSiwKkOh7wkm6VWh_EulBE-q34Iv6JFb4InM	2025-10-08 11:56:48.74546+05
\.


--
-- Name: accounts_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.accounts_customuser_groups_id_seq', 1, false);


--
-- Name: accounts_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.accounts_customuser_id_seq', 17, true);


--
-- Name: accounts_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.accounts_customuser_user_permissions_id_seq', 1, false);


--
-- Name: accounts_ledgerentry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.accounts_ledgerentry_id_seq', 15, true);


--
-- Name: accounts_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.accounts_order_id_seq', 29, true);


--
-- Name: accounts_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.accounts_stock_id_seq', 5, true);


--
-- Name: accounts_trading_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.accounts_trading_id_seq', 12, true);


--
-- Name: accounts_tradingposition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.accounts_tradingposition_id_seq', 12, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 32, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maryam
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 26, true);


--
-- Name: accounts_customuser_groups accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq UNIQUE (customuser_id, group_id);


--
-- Name: accounts_customuser_groups accounts_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser accounts_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser_user_permissions accounts_customuser_user_customuser_id_permission_9632a709_uniq; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser_user_customuser_id_permission_9632a709_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: accounts_customuser_user_permissions accounts_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser accounts_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_username_key UNIQUE (username);


--
-- Name: accounts_ledgerentry accounts_ledgerentry_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_ledgerentry
    ADD CONSTRAINT accounts_ledgerentry_pkey PRIMARY KEY (id);


--
-- Name: accounts_order accounts_order_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_order
    ADD CONSTRAINT accounts_order_pkey PRIMARY KEY (id);


--
-- Name: accounts_stock accounts_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_stock
    ADD CONSTRAINT accounts_stock_pkey PRIMARY KEY (id);


--
-- Name: accounts_stock accounts_stock_ticker_key; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_stock
    ADD CONSTRAINT accounts_stock_ticker_key UNIQUE (ticker);


--
-- Name: accounts_tradingaccount accounts_trading_account_number_key; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_tradingaccount
    ADD CONSTRAINT accounts_trading_account_number_key UNIQUE (account_number);


--
-- Name: accounts_tradingaccount accounts_trading_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_tradingaccount
    ADD CONSTRAINT accounts_trading_pkey PRIMARY KEY (id);


--
-- Name: accounts_tradingaccount accounts_trading_user_id_key; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_tradingaccount
    ADD CONSTRAINT accounts_trading_user_id_key UNIQUE (user_id);


--
-- Name: accounts_tradingposition accounts_tradingposition_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_tradingposition
    ADD CONSTRAINT accounts_tradingposition_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: accounts_tradingposition unique_account_stock; Type: CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_tradingposition
    ADD CONSTRAINT unique_account_stock UNIQUE (account_id, stock_ticker);


--
-- Name: accounts_customuser_groups_customuser_id_bc55088e; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_customuser_groups_customuser_id_bc55088e ON public.accounts_customuser_groups USING btree (customuser_id);


--
-- Name: accounts_customuser_groups_group_id_86ba5f9e; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_customuser_groups_group_id_86ba5f9e ON public.accounts_customuser_groups USING btree (group_id);


--
-- Name: accounts_customuser_user_permissions_customuser_id_0deaefae; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_customuser_user_permissions_customuser_id_0deaefae ON public.accounts_customuser_user_permissions USING btree (customuser_id);


--
-- Name: accounts_customuser_user_permissions_permission_id_aea3d0e5; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_customuser_user_permissions_permission_id_aea3d0e5 ON public.accounts_customuser_user_permissions USING btree (permission_id);


--
-- Name: accounts_customuser_username_722f3555_like; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_customuser_username_722f3555_like ON public.accounts_customuser USING btree (username varchar_pattern_ops);


--
-- Name: accounts_ledgerentry_account_id_7615ec66; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_ledgerentry_account_id_7615ec66 ON public.accounts_ledgerentry USING btree (account_id);


--
-- Name: accounts_order_account_id_47117414; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_order_account_id_47117414 ON public.accounts_order USING btree (account_id);


--
-- Name: accounts_order_stock_id_74aec32d; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_order_stock_id_74aec32d ON public.accounts_order USING btree (stock_id);


--
-- Name: accounts_stock_ticker_387e9406_like; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_stock_ticker_387e9406_like ON public.accounts_stock USING btree (ticker varchar_pattern_ops);


--
-- Name: accounts_trading_account_number_4d0bce95_like; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_trading_account_number_4d0bce95_like ON public.accounts_tradingaccount USING btree (account_number varchar_pattern_ops);


--
-- Name: accounts_tradingposition_account_id_eb4363d1; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX accounts_tradingposition_account_id_eb4363d1 ON public.accounts_tradingposition USING btree (account_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: maryam
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: accounts_customuser_user_permissions accounts_customuser__customuser_id_0deaefae_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser__customuser_id_0deaefae_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_groups accounts_customuser__customuser_id_bc55088e_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser__customuser_id_bc55088e_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_user_permissions accounts_customuser__permission_id_aea3d0e5_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser__permission_id_aea3d0e5_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_groups accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_ledgerentry accounts_ledgerentry_account_id_7615ec66_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_ledgerentry
    ADD CONSTRAINT accounts_ledgerentry_account_id_7615ec66_fk_accounts_ FOREIGN KEY (account_id) REFERENCES public.accounts_tradingaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_order accounts_order_account_id_47117414_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_order
    ADD CONSTRAINT accounts_order_account_id_47117414_fk_accounts_ FOREIGN KEY (account_id) REFERENCES public.accounts_tradingaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_order accounts_order_stock_id_74aec32d_fk_accounts_stock_id; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_order
    ADD CONSTRAINT accounts_order_stock_id_74aec32d_fk_accounts_stock_id FOREIGN KEY (stock_id) REFERENCES public.accounts_stock(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_tradingaccount accounts_trading_user_id_9784934f_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_tradingaccount
    ADD CONSTRAINT accounts_trading_user_id_9784934f_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_tradingposition accounts_tradingposi_account_id_eb4363d1_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.accounts_tradingposition
    ADD CONSTRAINT accounts_tradingposi_account_id_eb4363d1_fk_accounts_ FOREIGN KEY (account_id) REFERENCES public.accounts_tradingaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: maryam
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict JkDcJwCljediQR2HvhQmEaIErxR6WonBs1HIfkPGupGJCBOJf2ANNrQXIheJiQt

