# Generated by Django 5.2.7 on 2025-11-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-timestamp"]},
        ),
    ]
