# Generated by Django 5.2.6 on 2025-09-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trading',
            new_name='TradingAccount',
        ),
    ]
