# Generated by Django 5.2.6 on 2025-09-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tradingposition',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
