# Generated by Django 5.2.6 on 2025-09-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_ledgerentry_amount_alter_stock_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=12),
        ),
    ]
