# Generated by Django 5.2.6 on 2025-10-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_tradingaccount_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tradingaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
