# Generated by Django 5.2.6 on 2025-10-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order_updated_at_tradingaccount_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tradingposition',
            name='stock_ticker',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'transaction_type'], name='accounts_le_account_15be29_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['timestamp'], name='accounts_le_timesta_cc1845_idx'),
        ),
    ]
